const FETCH_COORDINATES = 'FETCH_COORDINATES_SUCCESS';
const FETCH_SHIPS = 'FETCH_SHIP_SUCCESS';
const UPDATE_SHIPS = 'UPDATE_SHIPS';
const FETCH_COORDINATES_SANK = 'FETCH_COORDINATES_SANK';

export default { FETCH_COORDINATES, FETCH_SHIPS, UPDATE_SHIPS, FETCH_COORDINATES_SANK };
